A fix for PR#201.  This patch may have unintended consequences so it is currently controlled by the registry option python.options.extendedClassLoader.  When this option is true (default), the following semantics are in effect.  When this option is false, the old semantics are in effect.  This option will be removed before 1.0 final.
Specifically,

loadClass(): Insert a new class search algorithm in between the shot
the Py state class loader has, and the shot the Java system class
loader has.  This new algorithm searches sys.path for the named .class
file and loads it if found.

This fixes PR#201 by allowing the class loader (i.e. our current
BytecodeLoader) that is loading an outer class have a shot at finding
and loading the anonymous inner class.  Without this patch, a variety
of errors can occur, depending on the state of your Java CLASSPATH;
either a NoClassDefFoundError or IllegalAccessException will get
thrown when trying to load the anonymous inner class.

open(): helper method

loadClass(String, byte[]) => loadClassFromBytes(String, byte[])